name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'  # Node.js
          cache: 'npm'

      - name: Clean node_modules and package-lock.json
        run: |
          rm -rf node_modules package-lock.json

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
        env:
          VITE_CLIENT_URL: https://cho-seunghee.github.io/cms

      - name: Debug build output
        run: |
          ls -la
          ls -la dist || echo "dist folder not found"
          ls -la build || echo "build folder not found"
        # Check if build or dist folder exists and list contents

      - name: Create 404.html
        run: cp dist/index.html dist/404.html || echo "Failed to copy index.html to 404.html"
        # Adjusted to dist; added error handling

      - name: Add .nojekyll
        run: touch dist/.nojekyll

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Adjusted to dist
          force_orphan: true